# Generated by Django 4.2.4 on 2023-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
